# Generated by Django 4.1.3 on 2022-11-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blog_num_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='num',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
