# Generated by Django 4.2.1 on 2023-05-27 08:13

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_blog_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='descriptiom',
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=markdownx.models.MarkdownxField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='coverImage',
            field=models.ImageField(upload_to='Static/Blogs'),
        ),
    ]
