# Generated by Django 4.1.3 on 2022-11-24 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('conID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('dateTime', models.DateTimeField(default=datetime.datetime(2022, 11, 24, 21, 12, 41, 962731))),
            ],
        ),
    ]
