# Generated by Django 4.1.3 on 2022-11-25 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='phone',
            field=models.CharField(default=3433333333, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 9, 4, 49, 163544)),
        ),
    ]
