# Generated by Django 4.1.3 on 2022-11-25 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactdata_phone_alter_contactdata_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 9, 8, 40, 378020)),
        ),
    ]
